### ISSUE TITLE
Darken/lighten functions

### ISSUE THREAD

**Issue by systemed** [systemed/glug#2]
See enormo-answer at http://stackoverflow.com/questions/5560248/programmatically-lighten-or-darken-a-hex-color-or-rgb-and-blend-colors for some sample code.

**Comment by pnorman** [comment]
Please please do not darken or lighten in HSL/HSV.

Lch is what I've worked in, but HUSL might work.

With [hsul-ruby](https://github.com/husl-colors/husl-ruby) it looks like you could do this with Husl.hex_to_husl, add or subtract to the lightness component, and then do Husl::husl_to_hex.

This actually looks simpler than the stackoverflow methods, since all the complexity is in the gem.

HSV and HSL came about in the 80s with the need to perform color calculations at 30 FPS on hardware less powerful than my calculator. The Lab colour calculations involve non-linear functions which are a big problem on computers without FPUs. Since glug only runs the calculations once when preprocessing to mapbox GL JSON, it's not a performance-critical calculation.

**Comment by pnorman** [comment]
Note: you'll still have to do something to handle stuff like `lighten(white, 100)` and other expressions which do not have a representable colour.. Generally, by limiting lightness to between 0 and 100.

**Comment by systemed** [comment]
This is doable nicely with the `chroma` gem. I've hacked up a method like this:

    require 'chroma'
    def chroma(v,method,p)
      ("#"+v.to_s(16).rjust(6,'0')).paint.send(method,p).to_hex.gsub('#','0x').to_i(16)
    end

which means we can do `chroma(0xD4E5F7, :darken, 10)`. But it'd be good to have it integrated into glug.
